============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.3.5, pluggy-1.5.0 -- /home/runner/work/CAS-741-Image-Correspondences/CAS-741-Image-Correspondences/src/.venv_ifcs/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/CAS-741-Image-Correspondences/CAS-741-Image-Correspondences
collecting ... collected 3 items

test/test_verifyOutput.py::test_check_match_uniqueness_valid PASSED      [ 33%]
test/test_verifyOutput.py::test_check_match_uniqueness_warns_for_same_ids PASSED [ 66%]
test/test_verifyOutput.py::test_check_match_uniqueness_warns_with_matches PASSED [100%]

============================== 3 passed in 0.01s ===============================
